### PR TITLE
Fix type defs from examples

### PR DESCRIPTION
**Pull request by sanak**
@Siedlerchr From PR #23, I separated `@types/ol-ext` related commits to this PR, so could you check this a bit ?
- comment: https://github.com/Siedlerchr/types-ol-ext/pull/23#issuecomment-869073613

Thanks,

### CODE REVIEW

**Comment by sanak** [comment]
Well, now I am checking `examples/style/map.style.font.html` in #23, and I am modifying `style/FontSymbol.ts.d`, but it will be another PR.

**Comment by Siedlerchr** [comment]
Okay, I have yesterday also worked on the controls so I will try to integrate this

**Comment by Siedlerchr** [comment]
Thanks, I integrate your changes into my PR and fixed some more overlay stuff. 
The only problem I encountered is that PopupFeature has a method `show` that is not compatible with the BaseTpye in Popup. So we may need to copy over some other methods

**Comment by sanak** [comment]
Okay, thanks for confirmation.

I will check it on the examples #23 PR and finish up that in today.

**Comment by sanak** [comment]
@Siedlerchr Well, I will check the following `PopupFeature` side by porting https://viglino.github.io/ol-ext/examples/popup/map.popup.feature.html example to TypeScript. (ETA is this weekend for other work.)
> Thanks, I integrate your changes into my PR and fixed some more overlay stuff.
> The only problem I encountered is that PopupFeature has a method `show` that is not compatible with the BaseTpye in Popup. So we may need to copy over some other methods

**Pull request merged**
