### PR TITLE
Support npm publish

### PR DESCRIPTION
**Pull request by sanak**
This still needs actual npm publish, so I am thinking to check publish on another branch at `@gtt-project/types-ol-ext`.

Here are some notes:
- Basically, follow https://github.com/hanreev/types-ol way, with minimum changes.
   - Use just bash commands in `package.json - scripts` instead of creating script: https://github.com/hanreev/types-ol/blob/master/scripts/prepareNpm.js
   - Move almost of `dependencies` to `devDependencies` ~~, then add `files` property (to use `./ol-ext` as contents folder)~~ in `package.json`.
- About npm installation instruction, follow current NPM package (https://www.npmjs.com/package/types-ol-ext) npm alias way.
   - https://docs.npmjs.com/cli/v7/commands/npm-install
      ```bash
      npm install <alias>@npm:<name>
      ```
- Add `PUBLISH.md` as npm publish instruction.

### CODE REVIEW

**Comment by sanak** [comment]
I found some issues, so I fixed those and confirmed that the following npm package seems to work correctly.
- https://www.npmjs.com/package/@gtt-project/types-ol-ext

The branch diff between this branch and `feature/npm-publish-gtt` is only as follows:  
https://github.com/gtt-project/types-ol-ext/compare/feature/npm-publish..feature/npm-publish-gtt

To publish fixed version, I executed the following command:
```bash
npm version prerelease
```

**Comment by Siedlerchr** [comment]
Thanks  for the work, now I shoudl be able to publish this on npm or do I need something else? (first time I am doing this=

**Comment by sanak** [comment]
> Thanks for the work, now I shoudl be able to publish this on npm or do I need something else? (first time I am doing this=

Thanks for quick merge!
It was also first time for me (as @sanak) at last night, so please try `PUBLISH.md` instruction with your `@siedlerchr` account. 😄 

Note that `npm unpublish` causes 24 hours lock from NPM, so after publish once, please consider to version up with `npm version` command. 😅 
- https://docs.npmjs.com/cli/v7/commands/npm-version
- https://www.npmjs.com/policies/unpublish

**Comment by Siedlerchr** [comment]
Yeahaw! Thanks a lot!  ありがとう  💯 
 https://www.npmjs.com/package/@siedlerchr/types-ol-ext
I also added you as contributor!

**Comment by sanak** [comment]
Okay. Thanks, too! 👍  🙇‍♂️

**Pull request merged**
