### PR TITLE
Updateto216

### PR DESCRIPTION
**Pull request by Siedlerchr**
Add missing particule classes and overlays
Fix some parameters

### CODE REVIEW

**Comment by Siedlerchr** [comment]
@sanak  I added the missing particule classes (Cloud, Rain etc) and in general the example works (/misc/map.animatedcanvas.html) , only when you tick an option in the checkbox it shows undefined error for the variables. 
Do you have an idea how to solve this? Would be nice if you could take a look.

**Comment by sanak** [comment]
@Siedlerchr Okay, let me check it tonight.

**Comment by sanak** [comment]
@Siedlerchr  
Well, when frontend (=html side) needs variables which are defined in TypeScript side, those needs to be passed as global window variables.

I added those at the bottom part, so could you check it ?
https://github.com/Siedlerchr/types-ol-ext/pull/70/commits/71a3fa00d3582e3e68361a415b4d497fb40255f9#diff-3a0409c973d88bdd640feb41055d9cf75faa30d4784c05926a98ac05a935b9b7R86-R102

I also modified `var` => `const` and removed unnecessary lines.

**Comment by Siedlerchr** [comment]
Ah cool! Thanks a lot. Seems pretty obvious now as I see it ;)

**Pull request merged**
