### PR TITLE
 Extract optional constructor parameters to interface

### PR DESCRIPTION
**Pull request by daboudii**

### CODE REVIEW

**Comment by Siedlerchr** [comment]
Thanks for your work.
If you want you can also take over this repo. I am currently busy with other projects.

**Comment by daboudii** [comment]
Ok, no problem. 
I would be happy to take over.

**Comment by Siedlerchr** [comment]
Cool! I first generated the types with jsdoc from the ol-ext repo and then manually reworked some stuff, e.g. moving to own files etc.
I oriented myself on the repo from https://github.com/hanreev/types-ol  to get started.

**Comment by daboudii** [comment]
Which tool did you use to generated the types from jsdoc ?

**Comment by Siedlerchr** [comment]
I used https://github.com/englercj/tsd-jsdoc as a starting point. Depends on the quality of the jsdoc in the orginal code, especially regarding types etc.

**Comment by daboudii** [comment]
I'm just waiting, do you give me access to this repo or I just take over on my personal fork ?

**Pull request merged**
