### PR TITLE
[WIP] Fix interactions

### LINKED ISSUE #31: Check and align interactions with ol-ext master

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fixes #31 

TODO: Define events

### CODE REVIEW

**Comment by Siedlerchr** [comment]
@Tomschi  I tried to follow your example to define events e..g in the `Delete` interaction, but I always get some TS errors/incompatible type in super class. Do you have any idea?

**Comment by sanak** [comment]
Well, if adding some examples is helpful, let me know about that, though my activity will be weekend for a while. 😄

**Comment by Siedlerchr** [comment]
I managed to get it working now, at least it "compiles"

**Comment by Tomschi** [comment]
> @Tomschi I tried to follow your example to define events e..g in the `Delete` interaction, but I always get some TS errors/incompatible type in super class. Do you have any idea?

Have solved the problems?

**Comment by Siedlerchr** [comment]
@Tomschi  Yes. I needed to copy over the events from the parent class, that helped

**Pull request merged**
