### PR TITLE
WIP Update to ol 7 and ol-ext 4

### PR DESCRIPTION
**Pull request by Siedlerchr**
I could not get the examples to work yet:

```
Uncaught TypeError: ol.ext is undefined
    js Base.js:10
    Webpack 11
[Base.js:10](webpack://siedlerchr/types-ol-ext/node_modules/ol-ext/util/input/Base.js)
    js Base.js:10
    Webpack 11
```

@sanak  Any idea if we need to change sth here or if ol-ext needs to change it?

### CODE REVIEW

**Comment by sanak** [comment]
> @sanak Any idea if we need to change sth here or if ol-ext needs to change it?

Okay. I will check it a bit by tomorrow.

**Comment by sanak** [comment]
Here is quick check result after applying https://github.com/Viglino/ol-ext/pull/856/files locally (edit `./node_modules/ol-ext/util/**.js` directly) then build examples.
I guess that significant error is only `style/map.style.font.ts` (except `animation/map.featureanimation.ts`), but I will try to solve those.

- animation
  - [ ] map.featureanimation.ts (#72, #86)
    ```
    Uncaught TypeError: FeatureAnimation_1.default[$(...).text(...)] is not a constructor
        at addFeatureAt (map.featureanimation.ts:115:5)
        at map.featureanimation.ts:134:7
    Uncaught ReferenceError: add10 is not defined
        at HTMLSelectElement.onchange (map.featureanimation.html:50:44)
    ```
- bar
  - [x] map.control.bar.ts
  - [x] map.control.button.ts
  - [x] map.control.editbar.ts
- canvas
  - [x] map.control.gridreference.ts
- control
  - [ ] map.control.geobookmark.ts
    ```
    Uncaught ReferenceError: bm is not defined
        at HTMLInputElement.onchange (map.control.geobookmark.html:53:113)
    ```
  - [x] map.switcher.popup.ts
- filter
  - [x] map.filter.crop.ts
- geom
  - [x] map.geom.cspline.ts
- interaction
  - [x] map.interaction.clip.ts
  - [x] map.interaction.drawregular.ts
- map
  - [x] map.layer.3d.2.ts
- misc
  - [x] map.animatedcanvas.ts
  - [x] map.compare.ts
  - [ ] map.input.ts
    ```
    Uncaught ReferenceError: dialog is not defined
        at HTMLButtonElement.onclick (map.input.html:109:37)
    ```
- popup
  - [x] map.fixedpopup.ts
  - [x] map.popup.feature.ts
  - [x] map.popup.ts
- search
  - [x] map.control.searchnominatim.ts
- storymap
  - [x] map.control.imageline.ts
- style
  - [ ] map.style.font.ts
    ```
    Uncaught TypeError: Cannot read properties of undefined (reading 'glyphs')
        at ./examples/style/map.style.font.ts (map.style.font.ts:49:41)
        at __webpack_require__ (bootstrap:19:1)
        at startup:4:1
        at startup:4:1
    ```
  - [ ] map.style.pattern.ts
    ```
    Uncaught ReferenceError: refresh is not defined
        at HTMLSelectElement.onchange (map.style.pattern.html:121:49)
    ```

**Comment by sanak** [comment]
@Siedlerchr  
I fixed some type defs/examples, so please check my additional commits, when you have a time.
Thanks,

**Comment by Siedlerchr** [comment]
Thanks looks good so far!

**Pull request merged**
