### PR TITLE
Try to add Cspline examples

### LINKED ISSUE #43: Add missing types for cspline
Declaration needs to be merged with the one for geometry

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fixes #43 

add remove layers to interaction

@sanak  Seems like I need your help again here.. I am stuck in the example with the cspline function on geometry
The problem is that it is a method directly on a geometry object. I already added a module declaration to augment it, but I can't get my head around it. It would be really cool if you have an idea.

### CODE REVIEW

**Comment by sanak** [comment]
@Siedlerchr Okay, let me check this tonight.

**Comment by sanak** [comment]
@Siedlerchr I just pushed the changes which solve the issue, so could you check it ?
commit diff: https://github.com/Siedlerchr/types-ol-ext/pull/71/commits/e8b2954b87cf977cb1e3ce620a400298b5ea8099

The main error reason seems to be just missing the following line.
```ts
import 'ol-ext/render/Cspline';
```

**Comment by sanak** [comment]
I forgot to rename `cspline` to `ol_coordinate_cspline`, so I added the commit.
commit diff: https://github.com/Siedlerchr/types-ol-ext/pull/71/commits/af27f6ff2c8209227d73f0dd1a9b5cae0f9359a4

I also confirmed that the function works locally with the following diff.
```diff
--- a/examples/geom/map.geom.cspline.ts
+++ b/examples/geom/map.geom.cspline.ts
@@ -6,7 +6,9 @@ import { Stamen, Vector } from 'ol/source';
 import { Style, Stroke } from 'ol/style';
 import VectorLayer from 'ol/layer/Vector';
 import CircleStyle from 'ol/style/Circle';
-import 'ol-ext/render/Cspline';
+// import 'ol-ext/render/Cspline';
+import { Coordinate } from 'ol/coordinate';
+import ol_coordinate_cspline from "ol-ext/render/Cspline";
 
 declare global {
   interface Window {
@@ -84,3 +86,6 @@ const mod = new Modify({ features });
 map.addInteraction(mod);
 
 window.vector = vector;
+
+const coords: Coordinate[] = [[0,0],[10,10]];
+console.log(ol_coordinate_cspline(coords));
```
=> 
cspline-console-log-output

**Comment by Siedlerchr** [comment]
Thank you very much! It works now :) Okay the solution was to simply import the whole module... Okay that makes sense now. Didn't think about it yesterday evening..

**Pull request merged**
