### PR TITLE
Fix imports and update typings, also fix vector3d

### LINKED ISSUE #52: Vector3D error
I am getting the following error when I try to add a Vector3D layer to my map: 

`Argument of type 'Vector3D' is not assignable to parameter of type 'BaseLayer'.
  Type 'Vector3D' is missing the following properties from type 'BaseLayer': on, once, un, className_, and 52 more.ts(2345)`

I am importing Vector3D as `import { Vector3D } from "ol-ext/source/Vector3D";` and use the map's `addLayer` method.

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fixes #52 
@sanak  I have adjusted the example following your script and in theory it works, however I always get:
I am a bit clueless. Do you have any idea?

```
Uncaught TypeError: Vector3D_1.Vector3D is not a constructor
    <anonymous> map.layer.3d.2.ts:36
    <anonymous> map.layer.3d.2.js:76425
    <anonymous> map.layer.3d.2.js:76427
```

### CODE REVIEW

**Comment by sanak** [comment]
@Siedlerchr Well, I will try to check it a bit tonight.

**Comment by sanak** [comment]
@Siedlerchr  
With the following changes, above error seems not to happen.
(But now getCoordinates error happens, so filling original `$.getJSON` call without jQuery is still necessary...)
```diff
--- a/@types/ol-ext/source/Vector3D.d.ts
+++ b/@types/ol-ext/source/Vector3D.d.ts
@@ -26,7 +26,7 @@ export type Height = ((f: Feature) => number) | string | number;
  *  @param {function|string|Number} options.height a height function (returns height giving a feature) or a popertie name for the height or a fixed value
  *  @param {Array<number>} options.center center of the view, default [.5,1]
  */
-export class Vector3D extends ImageLayer {
+export default class Vector3D extends ImageLayer {
     constructor(options?: Options);
 
     /**
diff --git a/examples/map/map.layer.3d.2.ts b/examples/map/map.layer.3d.2.ts
index 2580774..baaede8 100644
--- a/examples/map/map.layer.3d.2.ts
+++ b/examples/map/map.layer.3d.2.ts
@@ -5,7 +5,7 @@ import TileLayer from 'ol/layer/Tile';
 import { OSM } from 'ol/source';
 import VectorSource from 'ol/source/Vector';
 import { GeoJSON } from 'ol/format';
-import { Vector3D } from 'ol-ext/source/Vector3D';
+import Vector3D from 'ol-ext/source/Vector3D';
 import { Stroke, Style } from 'ol/style';
 import { Polygon } from 'ol/geom';
```

**Comment by Siedlerchr** [comment]
Thanks for the investigation, I really wonder why the named eports make a difference. Maybe a webpack config think
I think https://webpack.js.org/loaders/imports-loader/

**Comment by sanak** [comment]
Okay. I will try to implement remaining `$.getJSON` related part later tonight.

**Comment by sanak** [comment]
@Siedlerchr  
Sorry, I missed that you already implemented `$.getJSON` alternative by using `fetch` API.
I modified more on the example and committed/pushed it to this PR branch directly, so please check it after pulling the commit.
Thanks,

**Comment by Siedlerchr** [comment]
Thanks again for your help @sanak I added now default exports to other classes as well. 
I also updated to latest ol-ext version

**Comment by sanak** [comment]
@Siedlerchr  
Okay, no problem.

By the way, about default exports, I think that just following original ol-ext export definition (at JavaScript file's last line) will be enough.

For example, in above `Vector3D` class case, I just followed the original export definition.
https://github.com/Viglino/ol-ext/blob/master/src/source/Vector3D.js#L335
```js
export default ol_layer_Vector3D
```

**Pull request merged**
