### PR TITLE
Add empty index.d.ts file as entry point

### LINKED ISSUE #47: TS2688: Cannot find type definition file for 'ol-ext'
When building embedded examples, there is no error, but when I build [redmine_gtt](https://github.com/gtt-project/redmine_gtt) plugin, it shows the following error.
```
ERROR in /Users/sanak/Desktop/redmine_gtt/tsconfig.json
[tsl] ERROR
      TS2688: Cannot find type definition file for 'ol-ext'.
  The file is in the program because:
    Entry point for implicit type library 'ol-ext'
```

And after creating empty `types.d.ts` file in the root directory, then this error disappeared.

Here are the steps to reproduce.
```bash
$ git clone git@github.com:gtt-project/redmine_gtt.git -b feature/upgrade-types-ol-ext
$ cd redmine_gtt
$ yarn
$ npx webpack
:
ERROR in /Users/sanak/Desktop/redmine_gtt/tsconfig.json
[tsl] ERROR
      TS2688: Cannot find type definition file for 'ol-ext'.
  The file is in the program because:
    Entry point for implicit type library 'ol-ext'

webpack 5.24.4 compiled with 1 error in 12085 ms
```

```bash
$ touch node_modules/@types/ol-ext/types.d.ts
$ npx webpack
:
webpack 5.24.4 compiled with 3 warnings in 11320 ms
```

@Siedlerchr  
I set the entry point to `types.d.ts` in #13, because there was the file at that time,
- https://github.com/Siedlerchr/types-ol-ext/pull/13/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

but `types-ol` is using `index.d.ts` (default), so, I am thinking to change `package.json` as follows,
```diff
- "types": "types.d.ts",
+ "types": "index.d.ts",
```
then add empty `index.d.ts` file, but is this okay ?

### PR DESCRIPTION
**Pull request by sanak**
Fixes #47.

- Add empty `index.d.ts` file as entry point.

### CODE REVIEW

**Comment by sanak** [comment]
@Siedlerchr I noticed that `master` branch's `package.json` version is still `1.0.0`, so it may be better to merge this after upgrading `package.json` to track history collectly.

**Comment by Siedlerchr** [comment]
in my other open PR I already have the 0.0.1 commit included, maybe I can do a cherry pick to master

**Comment by sanak** [comment]
@Siedlerchr 
> in my other open PR I already have the 0.0.1 commit included, maybe I can do a cherry pick to master

Oh, I see.
By the way, about 6 days ago `1.1.0`, have you deployed from that PR (#46) branch ?
Then, it may be better to merge that branch before merging this PR.

**Comment by Siedlerchr** [comment]
I think I just didn't commit after npm publish

**Comment by sanak** [comment]
Okay, thanks for confirmation!

**Pull request merged**
