### PR TITLE
[WIP] Add missing classes

### PR DESCRIPTION
**Pull request by Siedlerchr**
update gitignore

### CODE REVIEW

**Comment by sanak** [comment]
@Siedlerchr 
Hi, I am not familiar with TypeScript, but I want to contribute (like validation) for the next `type-ol-ext` release.
But will this PR become the main next release base ?

Also, `ol-ext` side seems to have minor version up (`v3.1.19` => `v3.2.2`) at 17 May, but are you planning to follow the more recent version or just stick v3.1.19, once in next release ?
`ol-ext` diffs:
- `v3.1.19..v3.2.2`: https://github.com/Viglino/ol-ext/compare/v3.1.19..v3.2.2
- `v3.2.2..master`: https://github.com/Viglino/ol-ext/compare/v3.2.2..master

**Comment by Siedlerchr** [comment]
Hi, I'm trying to adjust it to the latest release/master of ol-ext

**Comment by sanak** [comment]
Okay, thanks for confirmation!
I am thinking to combine ol-ext examples to this repository for validation (test) purpose with my TypeScript learning & trial 😄 .

I will tell the progress when I reach a certain level, so please wait for a while. 🙇‍♂️

**Comment by Siedlerchr** [comment]
Thanks a lot! I will try to continue here as well, just atm busy with another [open-source project[(https://github.com/JabRef/jabref) ^^

**Comment by Siedlerchr** [comment]
merging for the moment

**Comment by sanak** [comment]
@Siedlerchr (CC: @Tomschi)  
> I am thinking to combine ol-ext examples to this repository for validation (test) purpose with my TypeScript learning & trial 😄 .

Sorry.
Before trying ol-ext example things, I wrongly started to try to generate type defs automatically from `ol-ext` master branch code with customizing `tsd-jsdoc` library... 🙇‍♂️ 😓 

Probably, my attempt will take a lot of time (over 2 weeks), so I will concentrate some example validation things, at first.

**Comment by Siedlerchr** [comment]
@sanak  I recently tried that as well to test if it works better now, but it's not really suitable. You still have to fix a lot of stuff  manually, incorrect types etc. You can take some of it as basis, but needs a lot of manual adjusting.
In fact, the initial repo here was partly generated by the automatic conversion. I am now trying to align it to the master branch.

**Comment by sanak** [comment]
@Siedlerchr
Okay, sure... Thanks for the information!

**Comment by Tomschi** [comment]
I think @Siedlerchr is right. Generating things is nice, but have its limitations. I think the only way is to fix the type definitions manually.

**Comment by sanak** [comment]
@Tomschi (CC: @Siedlerchr)  
Okay, sure...
Actually, some parts seems to be a quite hard (like making `XXXOptions` in one `*.ts.d` file).
Thanks for the confirmation !

**Pull request merged**
